### ISSUE TITLE
IndexError with Toyota theme

### ISSUE THREAD

**Issue by ChaseCares** [Coltonton/eon-custom-themes#5]
I ran the installer, Installed the boot logo, boot animation and then selected 4 to reboot, and received this error.

```
What resources do you want to install for the Toyota theme?
1. Boot Logo
2. Boot Animation
3. -Main Menu-
4. -Reboot-
Enter Index Value: 4
Traceback (most recent call last):
  File "/data/eon-custom-themes/install_theme.py", line 218, in <module>
    ti = ThemeInstaller()
  File "/data/eon-custom-themes/install_theme.py", line 87, in __init__
    self.start_loop()
  File "/data/eon-custom-themes/install_theme.py", line 96, in start_loop
    if self.install_function() == 'exit':
  File "/data/eon-custom-themes/install_theme.py", line 132, in install_function
    selected_option = self.theme_options[indexChoice]
IndexError: list index out of range
```

**Comment by Coltonton** [comment]
Thank you, issue is known. Haven’t got to fixing. It’s just the reboot command issint right.
